sonar.projectKey=app
sonar.projectName=Proyecto E-commerce
sonar.projectVersion=1.0

# 1. Dónde está el código fuente (Quitamos las pruebas de aquí)
sonar.sources=Backend,Frontend/src

# 2. Dónde están las pruebas (Definimos las carpetas de origen de tests)
# Añadimos Frontend/src (o donde sea que guardes tus .test.ts en el frente)
sonar.tests=Backend/test,Frontend/src

# 3. Extensiones de pruebas (Corregido para que acepte JS del backend y TS/TSX del frontend)
sonar.test.inclusions=Backend/test/**/*.js,Frontend/src/**/*.test.ts,Frontend/src/**/*.spec.ts,Frontend/src/**/*.test.tsx,Frontend/src/**/*.spec.tsx

# 4. Excluir del cálculo de Cobertura (Código que NO se puede o no vale la pena testear)
sonar.coverage.exclusions=Backend/config/db.js,Backend/seedProducts.js

# 5. Exclusiones Generales (Archivos que Sonar NO debe ni siquiera leer o indexar)
# Eliminamos .scannerwork por redundante y Backend/test de aquí (porque ya es un 'sonar.tests')
sonar.exclusions=\
  Backend/eslint.config.js,\
  Backend/coverage/**,\
  Backend/**/*.html,\
  Frontend/node_modules/**,\
  Frontend/dist/**

# 6. Rutas de los reportes de cobertura LCOV
sonar.javascript.lcov.reportPaths=Backend/coverage/lcov.info,Frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8